//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormCargaOP.WSLaNacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="contactos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class contactos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razon_socialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rfcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string impuestoField;
        
        private bool requiere_expediente_factField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FormCargaOP.WSLaNacion.ArrayOfDomicilios DomiciliosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FormCargaOP.WSLaNacion.ArrayOfTelefonos TelefonosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FormCargaOP.WSLaNacion.ArrayOfEmails EmailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FormCargaOP.WSLaNacion.ArrayOfRelaciones RelacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string operacion {
            get {
                return this.operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.operacionField, value) != true)) {
                    this.operacionField = value;
                    this.RaisePropertyChanged("operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string razon_social {
            get {
                return this.razon_socialField;
            }
            set {
                if ((object.ReferenceEquals(this.razon_socialField, value) != true)) {
                    this.razon_socialField = value;
                    this.RaisePropertyChanged("razon_social");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                if ((object.ReferenceEquals(this.rfcField, value) != true)) {
                    this.rfcField = value;
                    this.RaisePropertyChanged("rfc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                if ((object.ReferenceEquals(this.rolField, value) != true)) {
                    this.rolField = value;
                    this.RaisePropertyChanged("rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                if ((object.ReferenceEquals(this.guidField, value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string impuesto {
            get {
                return this.impuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.impuestoField, value) != true)) {
                    this.impuestoField = value;
                    this.RaisePropertyChanged("impuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool requiere_expediente_fact {
            get {
                return this.requiere_expediente_factField;
            }
            set {
                if ((this.requiere_expediente_factField.Equals(value) != true)) {
                    this.requiere_expediente_factField = value;
                    this.RaisePropertyChanged("requiere_expediente_fact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public FormCargaOP.WSLaNacion.ArrayOfDomicilios Domicilios {
            get {
                return this.DomiciliosField;
            }
            set {
                if ((object.ReferenceEquals(this.DomiciliosField, value) != true)) {
                    this.DomiciliosField = value;
                    this.RaisePropertyChanged("Domicilios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public FormCargaOP.WSLaNacion.ArrayOfTelefonos Telefonos {
            get {
                return this.TelefonosField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonosField, value) != true)) {
                    this.TelefonosField = value;
                    this.RaisePropertyChanged("Telefonos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public FormCargaOP.WSLaNacion.ArrayOfEmails Emails {
            get {
                return this.EmailsField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailsField, value) != true)) {
                    this.EmailsField = value;
                    this.RaisePropertyChanged("Emails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public FormCargaOP.WSLaNacion.ArrayOfRelaciones Relaciones {
            get {
                return this.RelacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.RelacionesField, value) != true)) {
                    this.RelacionesField = value;
                    this.RaisePropertyChanged("Relaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDomicilios", Namespace="http://tempuri.org/", ItemName="domicilios")]
    [System.SerializableAttribute()]
    public class ArrayOfDomicilios : System.Collections.Generic.List<FormCargaOP.WSLaNacion.domicilios> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfTelefonos", Namespace="http://tempuri.org/", ItemName="telefonos")]
    [System.SerializableAttribute()]
    public class ArrayOfTelefonos : System.Collections.Generic.List<FormCargaOP.WSLaNacion.telefonos> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfEmails", Namespace="http://tempuri.org/", ItemName="emails")]
    [System.SerializableAttribute()]
    public class ArrayOfEmails : System.Collections.Generic.List<FormCargaOP.WSLaNacion.emails> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfRelaciones", Namespace="http://tempuri.org/", ItemName="relaciones")]
    [System.SerializableAttribute()]
    public class ArrayOfRelaciones : System.Collections.Generic.List<FormCargaOP.WSLaNacion.relaciones> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="domicilios", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class domicilios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string calleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string barrioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string localidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string calle {
            get {
                return this.calleField;
            }
            set {
                if ((object.ReferenceEquals(this.calleField, value) != true)) {
                    this.calleField = value;
                    this.RaisePropertyChanged("calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroField, value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string barrio {
            get {
                return this.barrioField;
            }
            set {
                if ((object.ReferenceEquals(this.barrioField, value) != true)) {
                    this.barrioField = value;
                    this.RaisePropertyChanged("barrio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                if ((object.ReferenceEquals(this.localidadField, value) != true)) {
                    this.localidadField = value;
                    this.RaisePropertyChanged("localidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="telefonos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class telefonos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroField, value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="emails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class emails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        private bool certificaField;
        
        private bool generalField;
        
        private bool comprobantesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool certifica {
            get {
                return this.certificaField;
            }
            set {
                if ((this.certificaField.Equals(value) != true)) {
                    this.certificaField = value;
                    this.RaisePropertyChanged("certifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool general {
            get {
                return this.generalField;
            }
            set {
                if ((this.generalField.Equals(value) != true)) {
                    this.generalField = value;
                    this.RaisePropertyChanged("general");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool comprobantes {
            get {
                return this.comprobantesField;
            }
            set {
                if ((this.comprobantesField.Equals(value) != true)) {
                    this.comprobantesField = value;
                    this.RaisePropertyChanged("comprobantes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="relaciones", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class relaciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contacto_guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string contacto_guid {
            get {
                return this.contacto_guidField;
            }
            set {
                if ((object.ReferenceEquals(this.contacto_guidField, value) != true)) {
                    this.contacto_guidField = value;
                    this.RaisePropertyChanged("contacto_guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                if ((object.ReferenceEquals(this.rolField, value) != true)) {
                    this.rolField = value;
                    this.RaisePropertyChanged("rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="orden_publicitaria", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class orden_publicitaria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FormCargaOP.WSLaNacion.ArrayOfRenglon RenglonesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaField;
        
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUIAgenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazSocAgenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUIAnuncianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazSocAnuncianteField;
        
        private int PeriodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SennalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroOPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroOrdenField;
        
        private int IdOPMMASSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompetitivoDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableOrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosField;
        
        private int TotalGralMencionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaVencimientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public FormCargaOP.WSLaNacion.ArrayOfRenglon Renglones {
            get {
                return this.RenglonesField;
            }
            set {
                if ((object.ReferenceEquals(this.RenglonesField, value) != true)) {
                    this.RenglonesField = value;
                    this.RaisePropertyChanged("Renglones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CUIAgencia {
            get {
                return this.CUIAgenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.CUIAgenciaField, value) != true)) {
                    this.CUIAgenciaField = value;
                    this.RaisePropertyChanged("CUIAgencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RazSocAgencia {
            get {
                return this.RazSocAgenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.RazSocAgenciaField, value) != true)) {
                    this.RazSocAgenciaField = value;
                    this.RaisePropertyChanged("RazSocAgencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CUIAnunciante {
            get {
                return this.CUIAnuncianteField;
            }
            set {
                if ((object.ReferenceEquals(this.CUIAnuncianteField, value) != true)) {
                    this.CUIAnuncianteField = value;
                    this.RaisePropertyChanged("CUIAnunciante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RazSocAnunciante {
            get {
                return this.RazSocAnuncianteField;
            }
            set {
                if ((object.ReferenceEquals(this.RazSocAnuncianteField, value) != true)) {
                    this.RazSocAnuncianteField = value;
                    this.RaisePropertyChanged("RazSocAnunciante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Periodo {
            get {
                return this.PeriodoField;
            }
            set {
                if ((this.PeriodoField.Equals(value) != true)) {
                    this.PeriodoField = value;
                    this.RaisePropertyChanged("Periodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Sennal {
            get {
                return this.SennalField;
            }
            set {
                if ((object.ReferenceEquals(this.SennalField, value) != true)) {
                    this.SennalField = value;
                    this.RaisePropertyChanged("Sennal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string NroOP {
            get {
                return this.NroOPField;
            }
            set {
                if ((object.ReferenceEquals(this.NroOPField, value) != true)) {
                    this.NroOPField = value;
                    this.RaisePropertyChanged("NroOP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string NroOrden {
            get {
                return this.NroOrdenField;
            }
            set {
                if ((object.ReferenceEquals(this.NroOrdenField, value) != true)) {
                    this.NroOrdenField = value;
                    this.RaisePropertyChanged("NroOrden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int IdOPMMASS {
            get {
                return this.IdOPMMASSField;
            }
            set {
                if ((this.IdOPMMASSField.Equals(value) != true)) {
                    this.IdOPMMASSField = value;
                    this.RaisePropertyChanged("IdOPMMASS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string MarcaDescripcion {
            get {
                return this.MarcaDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaDescripcionField, value) != true)) {
                    this.MarcaDescripcionField = value;
                    this.RaisePropertyChanged("MarcaDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CompetitivoDescripcion {
            get {
                return this.CompetitivoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.CompetitivoDescripcionField, value) != true)) {
                    this.CompetitivoDescripcionField = value;
                    this.RaisePropertyChanged("CompetitivoDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ResponsableOrden {
            get {
                return this.ResponsableOrdenField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableOrdenField, value) != true)) {
                    this.ResponsableOrdenField = value;
                    this.RaisePropertyChanged("ResponsableOrden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Comentarios {
            get {
                return this.ComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosField, value) != true)) {
                    this.ComentariosField = value;
                    this.RaisePropertyChanged("Comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public int TotalGralMenciones {
            get {
                return this.TotalGralMencionesField;
            }
            set {
                if ((this.TotalGralMencionesField.Equals(value) != true)) {
                    this.TotalGralMencionesField = value;
                    this.RaisePropertyChanged("TotalGralMenciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaVencimientoField, value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfRenglon", Namespace="http://tempuri.org/", ItemName="renglon")]
    [System.SerializableAttribute()]
    public class ArrayOfRenglon : System.Collections.Generic.List<FormCargaOP.WSLaNacion.renglon> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="renglon", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class renglon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FormCargaOP.WSLaNacion.ArrayOfMencion MencionesField;
        
        private int NroDeRenglonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramaDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraDesdeCompraBloqHorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraHastaCompraBloqHorarioField;
        
        private int DuracionField;
        
        private double PrecioSegundoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoMaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemaMaterialusarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPublicidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public FormCargaOP.WSLaNacion.ArrayOfMencion Menciones {
            get {
                return this.MencionesField;
            }
            set {
                if ((object.ReferenceEquals(this.MencionesField, value) != true)) {
                    this.MencionesField = value;
                    this.RaisePropertyChanged("Menciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NroDeRenglon {
            get {
                return this.NroDeRenglonField;
            }
            set {
                if ((this.NroDeRenglonField.Equals(value) != true)) {
                    this.NroDeRenglonField = value;
                    this.RaisePropertyChanged("NroDeRenglon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProgramaDescripcion {
            get {
                return this.ProgramaDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramaDescripcionField, value) != true)) {
                    this.ProgramaDescripcionField = value;
                    this.RaisePropertyChanged("ProgramaDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HoraDesdeCompraBloqHorario {
            get {
                return this.HoraDesdeCompraBloqHorarioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraDesdeCompraBloqHorarioField, value) != true)) {
                    this.HoraDesdeCompraBloqHorarioField = value;
                    this.RaisePropertyChanged("HoraDesdeCompraBloqHorario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HoraHastaCompraBloqHorario {
            get {
                return this.HoraHastaCompraBloqHorarioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraHastaCompraBloqHorarioField, value) != true)) {
                    this.HoraHastaCompraBloqHorarioField = value;
                    this.RaisePropertyChanged("HoraHastaCompraBloqHorario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Duracion {
            get {
                return this.DuracionField;
            }
            set {
                if ((this.DuracionField.Equals(value) != true)) {
                    this.DuracionField = value;
                    this.RaisePropertyChanged("Duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double PrecioSegundo {
            get {
                return this.PrecioSegundoField;
            }
            set {
                if ((this.PrecioSegundoField.Equals(value) != true)) {
                    this.PrecioSegundoField = value;
                    this.RaisePropertyChanged("PrecioSegundo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CodigoMaterial {
            get {
                return this.CodigoMaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoMaterialField, value) != true)) {
                    this.CodigoMaterialField = value;
                    this.RaisePropertyChanged("CodigoMaterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TemaMaterialusar {
            get {
                return this.TemaMaterialusarField;
            }
            set {
                if ((object.ReferenceEquals(this.TemaMaterialusarField, value) != true)) {
                    this.TemaMaterialusarField = value;
                    this.RaisePropertyChanged("TemaMaterialusar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TipoPublicidad {
            get {
                return this.TipoPublicidadField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPublicidadField, value) != true)) {
                    this.TipoPublicidadField = value;
                    this.RaisePropertyChanged("TipoPublicidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfMencion", Namespace="http://tempuri.org/", ItemName="mencion")]
    [System.SerializableAttribute()]
    public class ArrayOfMencion : System.Collections.Generic.List<FormCargaOP.WSLaNacion.mencion> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mencion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class mencion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaDEEmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        private int UbicacionManualOrdenField;
        
        private int TotalMencionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdAvisoNotablesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DiaDEEmision {
            get {
                return this.DiaDEEmisionField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaDEEmisionField, value) != true)) {
                    this.DiaDEEmisionField = value;
                    this.RaisePropertyChanged("DiaDEEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UbicacionManualOrden {
            get {
                return this.UbicacionManualOrdenField;
            }
            set {
                if ((this.UbicacionManualOrdenField.Equals(value) != true)) {
                    this.UbicacionManualOrdenField = value;
                    this.RaisePropertyChanged("UbicacionManualOrden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalMenciones {
            get {
                return this.TotalMencionesField;
            }
            set {
                if ((this.TotalMencionesField.Equals(value) != true)) {
                    this.TotalMencionesField = value;
                    this.RaisePropertyChanged("TotalMenciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IdAvisoNotables {
            get {
                return this.IdAvisoNotablesField;
            }
            set {
                if ((object.ReferenceEquals(this.IdAvisoNotablesField, value) != true)) {
                    this.IdAvisoNotablesField = value;
                    this.RaisePropertyChanged("IdAvisoNotables");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="respuesta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="respuestaMenciones", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class respuestaMenciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FormCargaOP.WSLaNacion.ArrayOfRespuestaMencion resMencionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public FormCargaOP.WSLaNacion.ArrayOfRespuestaMencion resMenciones {
            get {
                return this.resMencionesField;
            }
            set {
                if ((object.ReferenceEquals(this.resMencionesField, value) != true)) {
                    this.resMencionesField = value;
                    this.RaisePropertyChanged("resMenciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfRespuestaMencion", Namespace="http://tempuri.org/", ItemName="respuestaMencion")]
    [System.SerializableAttribute()]
    public class ArrayOfRespuestaMencion : System.Collections.Generic.List<FormCargaOP.WSLaNacion.respuestaMencion> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="respuestaMencion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class respuestaMencion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdAvisoNotablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramaDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraDesdeCompraBloqHorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraHastaCompraBloqHorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoMaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaDEEmisionField;
        
        private int CantPautadaField;
        
        private int SegPautadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdAvisoNotables {
            get {
                return this.IdAvisoNotablesField;
            }
            set {
                if ((object.ReferenceEquals(this.IdAvisoNotablesField, value) != true)) {
                    this.IdAvisoNotablesField = value;
                    this.RaisePropertyChanged("IdAvisoNotables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProgramaDescripcion {
            get {
                return this.ProgramaDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramaDescripcionField, value) != true)) {
                    this.ProgramaDescripcionField = value;
                    this.RaisePropertyChanged("ProgramaDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HoraDesdeCompraBloqHorario {
            get {
                return this.HoraDesdeCompraBloqHorarioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraDesdeCompraBloqHorarioField, value) != true)) {
                    this.HoraDesdeCompraBloqHorarioField = value;
                    this.RaisePropertyChanged("HoraDesdeCompraBloqHorario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HoraHastaCompraBloqHorario {
            get {
                return this.HoraHastaCompraBloqHorarioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraHastaCompraBloqHorarioField, value) != true)) {
                    this.HoraHastaCompraBloqHorarioField = value;
                    this.RaisePropertyChanged("HoraHastaCompraBloqHorario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CodigoMaterial {
            get {
                return this.CodigoMaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoMaterialField, value) != true)) {
                    this.CodigoMaterialField = value;
                    this.RaisePropertyChanged("CodigoMaterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DiaDEEmision {
            get {
                return this.DiaDEEmisionField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaDEEmisionField, value) != true)) {
                    this.DiaDEEmisionField = value;
                    this.RaisePropertyChanged("DiaDEEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int CantPautada {
            get {
                return this.CantPautadaField;
            }
            set {
                if ((this.CantPautadaField.Equals(value) != true)) {
                    this.CantPautadaField = value;
                    this.RaisePropertyChanged("CantPautada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int SegPautado {
            get {
                return this.SegPautadoField;
            }
            set {
                if ((this.SegPautadoField.Equals(value) != true)) {
                    this.SegPautadoField = value;
                    this.RaisePropertyChanged("SegPautado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSLaNacion.wsimportSoap")]
    public interface wsimportSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        FormCargaOP.WSLaNacion.HelloWorldResponse HelloWorld(FormCargaOP.WSLaNacion.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<FormCargaOP.WSLaNacion.HelloWorldResponse> HelloWorldAsync(FormCargaOP.WSLaNacion.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento registro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addContacto", ReplyAction="*")]
        FormCargaOP.WSLaNacion.addContactoResponse addContacto(FormCargaOP.WSLaNacion.addContactoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addContacto", ReplyAction="*")]
        System.Threading.Tasks.Task<FormCargaOP.WSLaNacion.addContactoResponse> addContactoAsync(FormCargaOP.WSLaNacion.addContactoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento registro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addOrden", ReplyAction="*")]
        FormCargaOP.WSLaNacion.addOrdenResponse addOrden(FormCargaOP.WSLaNacion.addOrdenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addOrden", ReplyAction="*")]
        System.Threading.Tasks.Task<FormCargaOP.WSLaNacion.addOrdenResponse> addOrdenAsync(FormCargaOP.WSLaNacion.addOrdenRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechaDesde del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarMenciones", ReplyAction="*")]
        FormCargaOP.WSLaNacion.consultarMencionesResponse consultarMenciones(FormCargaOP.WSLaNacion.consultarMencionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarMenciones", ReplyAction="*")]
        System.Threading.Tasks.Task<FormCargaOP.WSLaNacion.consultarMencionesResponse> consultarMencionesAsync(FormCargaOP.WSLaNacion.consultarMencionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public FormCargaOP.WSLaNacion.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(FormCargaOP.WSLaNacion.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormCargaOP.WSLaNacion.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(FormCargaOP.WSLaNacion.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addContactoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addContacto", Namespace="http://tempuri.org/", Order=0)]
        public FormCargaOP.WSLaNacion.addContactoRequestBody Body;
        
        public addContactoRequest() {
        }
        
        public addContactoRequest(FormCargaOP.WSLaNacion.addContactoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addContactoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FormCargaOP.WSLaNacion.contactos registro;
        
        public addContactoRequestBody() {
        }
        
        public addContactoRequestBody(FormCargaOP.WSLaNacion.contactos registro) {
            this.registro = registro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addContactoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addContactoResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormCargaOP.WSLaNacion.addContactoResponseBody Body;
        
        public addContactoResponse() {
        }
        
        public addContactoResponse(FormCargaOP.WSLaNacion.addContactoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addContactoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addContactoResult;
        
        public addContactoResponseBody() {
        }
        
        public addContactoResponseBody(string addContactoResult) {
            this.addContactoResult = addContactoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addOrdenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addOrden", Namespace="http://tempuri.org/", Order=0)]
        public FormCargaOP.WSLaNacion.addOrdenRequestBody Body;
        
        public addOrdenRequest() {
        }
        
        public addOrdenRequest(FormCargaOP.WSLaNacion.addOrdenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addOrdenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FormCargaOP.WSLaNacion.orden_publicitaria registro;
        
        public addOrdenRequestBody() {
        }
        
        public addOrdenRequestBody(FormCargaOP.WSLaNacion.orden_publicitaria registro) {
            this.registro = registro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addOrdenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addOrdenResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormCargaOP.WSLaNacion.addOrdenResponseBody Body;
        
        public addOrdenResponse() {
        }
        
        public addOrdenResponse(FormCargaOP.WSLaNacion.addOrdenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addOrdenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FormCargaOP.WSLaNacion.respuesta addOrdenResult;
        
        public addOrdenResponseBody() {
        }
        
        public addOrdenResponseBody(FormCargaOP.WSLaNacion.respuesta addOrdenResult) {
            this.addOrdenResult = addOrdenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarMencionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarMenciones", Namespace="http://tempuri.org/", Order=0)]
        public FormCargaOP.WSLaNacion.consultarMencionesRequestBody Body;
        
        public consultarMencionesRequest() {
        }
        
        public consultarMencionesRequest(FormCargaOP.WSLaNacion.consultarMencionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarMencionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechaDesde;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechaHasta;
        
        public consultarMencionesRequestBody() {
        }
        
        public consultarMencionesRequestBody(string fechaDesde, string fechaHasta) {
            this.fechaDesde = fechaDesde;
            this.fechaHasta = fechaHasta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarMencionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarMencionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormCargaOP.WSLaNacion.consultarMencionesResponseBody Body;
        
        public consultarMencionesResponse() {
        }
        
        public consultarMencionesResponse(FormCargaOP.WSLaNacion.consultarMencionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultarMencionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FormCargaOP.WSLaNacion.respuestaMenciones consultarMencionesResult;
        
        public consultarMencionesResponseBody() {
        }
        
        public consultarMencionesResponseBody(FormCargaOP.WSLaNacion.respuestaMenciones consultarMencionesResult) {
            this.consultarMencionesResult = consultarMencionesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsimportSoapChannel : FormCargaOP.WSLaNacion.wsimportSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsimportSoapClient : System.ServiceModel.ClientBase<FormCargaOP.WSLaNacion.wsimportSoap>, FormCargaOP.WSLaNacion.wsimportSoap {
        
        public wsimportSoapClient() {
        }
        
        public wsimportSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsimportSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsimportSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsimportSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormCargaOP.WSLaNacion.HelloWorldResponse FormCargaOP.WSLaNacion.wsimportSoap.HelloWorld(FormCargaOP.WSLaNacion.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            FormCargaOP.WSLaNacion.HelloWorldRequest inValue = new FormCargaOP.WSLaNacion.HelloWorldRequest();
            inValue.Body = new FormCargaOP.WSLaNacion.HelloWorldRequestBody();
            FormCargaOP.WSLaNacion.HelloWorldResponse retVal = ((FormCargaOP.WSLaNacion.wsimportSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormCargaOP.WSLaNacion.HelloWorldResponse> FormCargaOP.WSLaNacion.wsimportSoap.HelloWorldAsync(FormCargaOP.WSLaNacion.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormCargaOP.WSLaNacion.HelloWorldResponse> HelloWorldAsync() {
            FormCargaOP.WSLaNacion.HelloWorldRequest inValue = new FormCargaOP.WSLaNacion.HelloWorldRequest();
            inValue.Body = new FormCargaOP.WSLaNacion.HelloWorldRequestBody();
            return ((FormCargaOP.WSLaNacion.wsimportSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormCargaOP.WSLaNacion.addContactoResponse FormCargaOP.WSLaNacion.wsimportSoap.addContacto(FormCargaOP.WSLaNacion.addContactoRequest request) {
            return base.Channel.addContacto(request);
        }
        
        public string addContacto(FormCargaOP.WSLaNacion.contactos registro) {
            FormCargaOP.WSLaNacion.addContactoRequest inValue = new FormCargaOP.WSLaNacion.addContactoRequest();
            inValue.Body = new FormCargaOP.WSLaNacion.addContactoRequestBody();
            inValue.Body.registro = registro;
            FormCargaOP.WSLaNacion.addContactoResponse retVal = ((FormCargaOP.WSLaNacion.wsimportSoap)(this)).addContacto(inValue);
            return retVal.Body.addContactoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormCargaOP.WSLaNacion.addContactoResponse> FormCargaOP.WSLaNacion.wsimportSoap.addContactoAsync(FormCargaOP.WSLaNacion.addContactoRequest request) {
            return base.Channel.addContactoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormCargaOP.WSLaNacion.addContactoResponse> addContactoAsync(FormCargaOP.WSLaNacion.contactos registro) {
            FormCargaOP.WSLaNacion.addContactoRequest inValue = new FormCargaOP.WSLaNacion.addContactoRequest();
            inValue.Body = new FormCargaOP.WSLaNacion.addContactoRequestBody();
            inValue.Body.registro = registro;
            return ((FormCargaOP.WSLaNacion.wsimportSoap)(this)).addContactoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormCargaOP.WSLaNacion.addOrdenResponse FormCargaOP.WSLaNacion.wsimportSoap.addOrden(FormCargaOP.WSLaNacion.addOrdenRequest request) {
            return base.Channel.addOrden(request);
        }
        
        public FormCargaOP.WSLaNacion.respuesta addOrden(FormCargaOP.WSLaNacion.orden_publicitaria registro) {
            FormCargaOP.WSLaNacion.addOrdenRequest inValue = new FormCargaOP.WSLaNacion.addOrdenRequest();
            inValue.Body = new FormCargaOP.WSLaNacion.addOrdenRequestBody();
            inValue.Body.registro = registro;
            FormCargaOP.WSLaNacion.addOrdenResponse retVal = ((FormCargaOP.WSLaNacion.wsimportSoap)(this)).addOrden(inValue);
            return retVal.Body.addOrdenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormCargaOP.WSLaNacion.addOrdenResponse> FormCargaOP.WSLaNacion.wsimportSoap.addOrdenAsync(FormCargaOP.WSLaNacion.addOrdenRequest request) {
            return base.Channel.addOrdenAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormCargaOP.WSLaNacion.addOrdenResponse> addOrdenAsync(FormCargaOP.WSLaNacion.orden_publicitaria registro) {
            FormCargaOP.WSLaNacion.addOrdenRequest inValue = new FormCargaOP.WSLaNacion.addOrdenRequest();
            inValue.Body = new FormCargaOP.WSLaNacion.addOrdenRequestBody();
            inValue.Body.registro = registro;
            return ((FormCargaOP.WSLaNacion.wsimportSoap)(this)).addOrdenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormCargaOP.WSLaNacion.consultarMencionesResponse FormCargaOP.WSLaNacion.wsimportSoap.consultarMenciones(FormCargaOP.WSLaNacion.consultarMencionesRequest request) {
            return base.Channel.consultarMenciones(request);
        }
        
        public FormCargaOP.WSLaNacion.respuestaMenciones consultarMenciones(string fechaDesde, string fechaHasta) {
            FormCargaOP.WSLaNacion.consultarMencionesRequest inValue = new FormCargaOP.WSLaNacion.consultarMencionesRequest();
            inValue.Body = new FormCargaOP.WSLaNacion.consultarMencionesRequestBody();
            inValue.Body.fechaDesde = fechaDesde;
            inValue.Body.fechaHasta = fechaHasta;
            FormCargaOP.WSLaNacion.consultarMencionesResponse retVal = ((FormCargaOP.WSLaNacion.wsimportSoap)(this)).consultarMenciones(inValue);
            return retVal.Body.consultarMencionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormCargaOP.WSLaNacion.consultarMencionesResponse> FormCargaOP.WSLaNacion.wsimportSoap.consultarMencionesAsync(FormCargaOP.WSLaNacion.consultarMencionesRequest request) {
            return base.Channel.consultarMencionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormCargaOP.WSLaNacion.consultarMencionesResponse> consultarMencionesAsync(string fechaDesde, string fechaHasta) {
            FormCargaOP.WSLaNacion.consultarMencionesRequest inValue = new FormCargaOP.WSLaNacion.consultarMencionesRequest();
            inValue.Body = new FormCargaOP.WSLaNacion.consultarMencionesRequestBody();
            inValue.Body.fechaDesde = fechaDesde;
            inValue.Body.fechaHasta = fechaHasta;
            return ((FormCargaOP.WSLaNacion.wsimportSoap)(this)).consultarMencionesAsync(inValue);
        }
    }
}
